### ISSUE TITLE
VsCode 1.2.0: Console errors and no handler for nim.run

### ISSUE THREAD

**Issue by partisanyc** [pragmagic/vscode-nim#14]
Hi, 

I've just installed VsCode 1.2.0, nim 0.14.0, nimsuggest, nimble. I installed vscode-nim, and while syntax highlighting works, I get the following errors when attempting to build or run, respectively:

- No handler found for the command: 'nim.build'. An extension might be missing an activation event.
- No handler found for the command: 'nim.run'. An extension might be missing an activation event.

Checking the developer console, I see the following. Your help is appreciated. 

`//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:92 [Extension Host] Activating extension `kosz78.nim` failed: ENOENT: no such file or directory, stat '/home/leif/undefined'.(anonymous function) @ //usr/share/code/resources/app/out/vs/workbench/workbench.main.js:92
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:92 [Extension Host] Activating extension `kosz78.nim` failed:  ENOENT: no such file or directory, stat '/home/leif/undefined'(anonymous function) @ //usr/share/code/resources/app/out/vs/workbench/workbench.main.js:92
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:92 [Extension Host] Here is the error stack:  Error: ENOENT: no such file or directory, stat '/home/leif/undefined'
    at Error (native)
    at fs.statSync (fs.js:897:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:263:16)
    at Object.initNimSuggest (/home/leif/.vscode/extensions/kosz78.nim-0.5.1/out/src/nimUtils.js:26:31)
    at activate (/home/leif/.vscode/extensions/kosz78.nim-0.5.1/out/src/nimMain.js:23:16)
    at Function.t._callActivateOptional (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:24266)
    at Function.t._callActivate (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:24051)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:12:23923
    at Object.h [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13179)
    at Object.__dirname.undefined.M.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:16341)
    at __dirname.undefined.t.Class.define._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:18167)
    at __dirname.undefined.t.Class.define._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:17608)
    at d (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:21265)
    at z.then.a.(anonymous function) (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:21489)
    at Object.h [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:13179)
    at Object.__dirname.undefined.M.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:5:16341)
//usr/share/code/resources/app/out/vs/workbench/workbench.main.js:73 Activating extension `kosz78.nim` failed: ENOENT: no such file or directory, stat '/home/leif/undefined'.t.$localShowMessage @ //usr/share/code/resources/app/out/vs/workbench/workbench.main.js:73
messageService.ts:119 No handler found for the command: 'nim.build'. An extension might be missing an activation event.e.doShow @ messageService.ts:119e.show @ messageService.ts:103e.resume @ messageService.ts:62(anonymous function) @ workbench.ts:638e.invoke @ callbackList.ts:63e.fire @ event.ts:107(anonymous function) @ quickOpenController.ts:4671

**Comment by kosz78** [comment]
Hi, it seems the extension cannot found nim installation correctly. Could you please check that nim can be found in you search path, by exec ` which nim` in terminal and also specify what OS you are using

**Comment by partisanyc** [comment]
Thanks for the response. I began to suspect that as well. I am on Ubuntu 14.04. Terminal `which nim` returns nothing, but `type nim` returns the correct path. I am also able to run nim from terminal with no problem.

**Comment by partisanyc** [comment]
Tthe instructions from the following issue helped:
https://github.com/zah/nim.vim/issues/35

Which recommended the following:
echo 'export PATH=$PATH:$your_install_dir/bin' >> ~/.profile

I had added my directory to PATH, but for some reason, it wasn't found by `which nim`. Removing all my attempts and using the command above did the trick and it works now. Thank you.
