### ISSUE TITLE
Timeout after 1000 ms: Error: Timeout after 1000 ms

### ISSUE THREAD

**Issue by haiodo** [pragmagic/vscode-nim#3]
Timeout after 1000 ms: Error: Timeout after 1000 ms
    at null._onTimeout (/Users/haiodo/.vscode/extensions/kosz78.nim-0.2.0/out/src/nimUtils.js:101:20)
    at Timer.listOnTimeout (timers.js:89:15)

**Comment by endragor** [comment]
This was fixed yesterday.
