### ISSUE TITLE
Extension crashes when opening a nim file

### ISSUE THREAD

**Issue by couven92** [pragmagic/vscode-nim#59]
From the crash log it seems this is a timeout issue when launching nimsuggest. There should be configuration setting to enable users to set their own timeouts.

Crash log:
```
extensionHost.ts:335 [Extension Host] ,,Nim Compiler Version 0.17.1 (2017-08-24) [Windows: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 82453825e98872862fc0adab536d2dd8c6f24116
active boot switches: -d:release --gc:markAndSweep

extensionHost.ts:335 [Extension Host] Nimsuggest version: 0.17.1
extensionHost.ts:335 [Extension Host] C:\Users\fra006\.vscode\extensions\kosz78.nim-0.5.26
extensionHost.ts:335 [Extension Host] 51300

extensionHost.ts:335 [Extension Host] rejected promise not handled within 1 second
t.logExtensionHostMessage @ extensionHost.ts:335
(anonymous) @ extensionHost.ts:188
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
shell.ts:423 Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (C:\Users\fra006\.vscode\extensions\kosz78.nim-0.5.26\out\src\nimIndexer.js:61:54)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\fra006\.vscode\extensions\kosz78.nim-0.5.26\out\src\nimIndexer.js:8:58)
    at process._tickCallback (internal/process/next_tick.js:103:7)
e.onUnexpectedError @ shell.ts:423
(anonymous) @ shell.ts:383
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:139
t.onUnexpectedExtHostError @ mainThreadErrors.ts:13
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by couven92** [comment]
Yes, the log states that I am using nimsuggest compiled from devel, but I have confirmed that the same issue occurs on vanilla 0.17.0 nimsuggest.
