### ISSUE TITLE
autocompletion doesn't work

### ISSUE THREAD

**Issue by kobi2187** [pragmagic/vscode-nim#72]
Nim Extension version: 0.5.27 (27 Sep 2017)

VSCode version:
Version 1.19.0-insider
Commit 0fbdfff167653b233231259ceb3109f0931887ef
Date 2017-11-09T06:19:28.857Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

On linux mint.

What other information can I give to figure out the problem?

**Comment by kosz78** [comment]
Open `Help->Toggle Developer Tools` and copy log information for `Log view`

**Comment by kobi2187** [comment]
[/home/kobi/.vscode-insiders/extensions/ms-vscode.cpptools-0.14.2]: Command `workbench.action.gotoSymbol` appears multiple times in the `commands` section.
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9 [/home/kobi/.vscode-insiders/extensions/ms-vscode.cpptools-0.14.2]: Command `workbench.action.showAllSymbols` appears multiple times in the `commands` section.
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] vscode-icons is active! (at activate (/home/kobi/.vscode-insiders/extensions/robertohuertasm.vscode-icons-7.18.1/out/src/index.js:41:13))
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] [Guides] Sending usage statistics... (at Guides.sendUsagesAndStats (/home/kobi/.vscode-insiders/extensions/spywhere.guides-0.9.0/out/extension.js:609:17))
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] /home/kobi/.vscode-insiders/extensions/kosz78.nim-0.5.27 (at activate (/home/kobi/.vscode-insiders/extensions/kosz78.nim-0.5.27/out/src/nimMain.js:53:13))
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10 [plrenaudin.gotolastedit] Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at saveChangePosition (/home/kobi/.vscode-insiders/extensions/plrenaudin.gotolastedit-0.6.2/extension.js:29:42)
	at _onEvent (/home/kobi/.vscode-insiders/extensions/plrenaudin.gotolastedit-0.6.2/extension.js:13:9)
	at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84389)
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86111)
	at e.$acceptDirtyStateChanged (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:428190)
	at t.e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:510061)
	at e._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355208)
	at e._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354898)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353925
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355844
e.onUnexpectedError @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10 [plrenaudin.gotolastedit] Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at _onEvent (/home/kobi/.vscode-insiders/extensions/plrenaudin.gotolastedit-0.6.2/extension.js:11:63)
	at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84389)
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86111)
	at e.$acceptDirtyStateChanged (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:428190)
	at e.$acceptModelSaved (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:427973)
	at t.e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:510061)
	at e._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355208)
	at e._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354898)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353925
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355844
e.onUnexpectedError @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10 [plrenaudin.gotolastedit] Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at _onEvent (/home/kobi/.vscode-insiders/extensions/plrenaudin.gotolastedit-0.6.2/extension.js:11:63)
	at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84389)
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86111)
	at e.$acceptDirtyStateChanged (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:428190)
	at t.e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:510061)
	at e._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355208)
	at e._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354898)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353925
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355844
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:85106
e.onUnexpectedError @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10 [plrenaudin.gotolastedit] Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at _onEvent (/home/kobi/.vscode-insiders/extensions/plrenaudin.gotolastedit-0.6.2/extension.js:11:63)
	at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84389)
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86111)
	at e.$acceptDirtyStateChanged (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:428190)
	at e.$acceptModelSaved (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:427973)
	at t.e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:510061)
	at e._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355208)
	at e._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354898)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353925
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355844
e.onUnexpectedError @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10 [plrenaudin.gotolastedit] Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at _onEvent (/home/kobi/.vscode-insiders/extensions/plrenaudin.gotolastedit-0.6.2/extension.js:11:63)
	at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84389)
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86111)
	at e.$acceptDirtyStateChanged (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:428190)
	at t.e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:510061)
	at e._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355208)
	at e._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354898)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353925
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355844
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:85106
e.onUnexpectedError @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] [Guides] Error while sending usage statistics: undefined (at Request.request [as _callback] (/home/kobi/.vscode-insiders/extensions/spywhere.guides-0.9.0/out/extension.js:638:25))
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:9 [Extension Host] [Guides] Usage statistics will retry in the next 5 minutes (at Request.request [as _callback] (/home/kobi/.vscode-insiders/extensions/spywhere.guides-0.9.0/out/extension.js:646:25))
/usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10 [plrenaudin.gotolastedit] Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
	at _onEvent (/home/kobi/.vscode-insiders/extensions/plrenaudin.gotolastedit-0.6.2/extension.js:11:63)
	at e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:84389)
	at e.fire (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:86111)
	at e.$acceptDirtyStateChanged (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:428190)
	at e.$acceptModelSaved (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:427973)
	at t.e.invoke (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:510061)
	at e._invokeHandler (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355208)
	at e._receiveOneMessage (/usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:354898)
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:353925
	at /usr/share/code-insiders/resources/app/out/vs/workbench/node/extensionHostProcess.js:4:355844
e.onUnexpectedError @ /usr/share/code-insiders/resources/app/out/vs/workbench/workbench.main.js:10
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
raw.marked.js:15 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by kobi2187** [comment]
please contact me by email:
kobi2187 at gmail
if you need better interaction with me :-)

**Comment by nc-x** [comment]
@kobi2187 Do you have nimsuggest in PATH env variable?

I also had this issue of autocompletion not working but it was because I had compiled nim from source but forgot to compile nimsuggest.

This extension does not provide any warning/error/notification if nimsuggest is not found. 
@kosz78 It would be better to atleast have a notification if nimsuggest is not found.
